#!/bin/bash
# 
# This sets up static public ip address for all public

# Lots of mapping bc bash doesn't support multi dimentional arrays
declare -A EXTERNAL_IPS=(
    ['joey.vtluug.org']='128.173.88.191'            # router/dns
    ['crashandburn.vtluug.org']='128.173.89.244'    # ovirt
    ['sczi.vtluug.org']='128.173.88.78'             # web
    ['acidburn.vtluug.org']='128.173.89.245'        # shell
    ['zerocool.vtluug.org']='128.173.89.247'        # freeipa
    ['mirror.vtluug.org']='128.173.89.246'          # mirror
)

# This maps all the internal ips *not* run in ovirt
declare -A INTERNAL_IPS=(
    ['joey.vtluug.org']='10.99.0.1'             # router/dns
    ['crashandburn.vtluug.org']='10.99.0.2'     # ovirt
    ['sczi.vtluug.org']='10.99.0.3'             # web
    ['acidburn.vtluug.org']='10.99.0.4'         # shell
    ['zerocool.vtluug.org']='10.99.0.5'         # freeipa
    ['mirror.vtluug.org']='10.99.0.6'           # mirror
    ['cyberdelia.vtluug.org']='10.99.0.7'       # nas
)

# Maps hostname to distribution
declare -A DISTRIBUTIONS=(
    ['joey.vtluug.org']='centos7'           # router/dns
    ['crashandburn.vtluug.org']='centos7'   # ovirt
    ['sczi.vtluug.org']='centos7'           # web
    ['acidburn.vtluug.org']='debian9'       # shell
    ['zerocool.vtluug.org']='centos7'       # freeipa
    ['mirror.vtluug.org']='centos7'         # mirror
    ['cyberdelia.vtluug.org']='centos7'     # nas
)

# Hostname should've been set during installation
HOSTNAME=$(hostname -f)
HOSTNAME='joey.vtluug.org'
INTERNAL_IP=${INTERNAL_IPS[$HOSTNAME]}
EXTERNAL_IP=${EXTERNAL_IPS[$HOSTNAME]}

# Checks for valid input
function check_input {
    # Check for interface argument
    if [[ $# -eq 0 ]]
    then
        echo "Usage: $0 <interface>"
        exit 1
    fi
    # Check for invalid hostname
    if [[ "$INTERNAL_IP" == '' ]]
    then
        echo "Hostname Invalid: $HOSTNAME"
        exit 1
    fi
}

function setip_centos7 {
    # Setup variables
    INTERFACE=$1
    UUID=$(uuidgen $INTERFACE)
    FILE="/etc/sysconfig/network-scripts/ifcfg-$INTERFACE"

    # Print out what we're doing
    echo "Interface: $INTERFACE"
    echo "Hostname: $HOSTNAME"
    echo "Internal IP: $INTERNAL_IP"
    echo "External IP: $EXTERNAL_IP"


# Generate config
CONFIG="'# Generated by VTLUUG networking scripts for CentoOS 7
# see ifcfg-$INTERFACE.<timestamp> for older versions
TYPE=\"Ethernet\"
PROXY_METHOD=\"none\"
BROWSER_ONLY=\"no\"
DEFROUTE=\"yes\"
IPV4_FAILURE_FATAL=\"no\"
IPV6INIT=\"yes\"
IPV6_AUTOCONF=\"yes\"
IPV6_DEFROUTE=\"yes\"
IPV6_FAILURE_FATAL=\"no\"
IPV6_ADDR_GEN_MODE=\"stable-privacy\"
NAME=\"$INTERFACE\"
UUID=\"$UUID\"
DEVICE=\"$INTERFACE\"
ONBOOT=\"yes\"
NM_CONTROLLED=\"no\"
BOOTPROTO=\"static\"
IPADDR0=\"$INTERNAL_IP\"
NETMASK0=\"255.255.255.0\"
"

    # Add Secondary IP if necessary
    if [[ "$EXTERNAL_IP" != "" ]]
    then
CONFIG+="# Additional IPs
IPADDR1=\"$EXTERNAL_IP\"
GATEWAY1=\"128.173.88.1\"
NETMASK1=\"255.255.252.0\"
"
    fi

    # Backup current file
    if [[ -e $FILE ]]
    then
        mv $FILE $FILE.$(date +%Y%m%d%H%M%)
    fi

    # Save to file
    echo 'NOTHING HAPPENS YET'
    #printf "$CONFIG" > $FILE
}



# Checks for interface and valid hostname
check_input $1

# Generate appropriate config
DISTRIBUTION=${DISTRIBUTIONS[$HOSTNAME]}
if [[ "$DISTRIBUTION" == 'centos7' ]]
then
    setip_centos7 $1 $INTERNAL_IP
elif [[ "$DISTRIBUTION" == 'debian9' ]]
then
    setip_debian9 $1 $INTERNAL_IP
else
    echo "Distribution Unsupported: $DISTRIBUTION"
fi
